Cannot exec 'CUDA_VISIBLE_DEVICES=1': No such file or directory
Traceback (most recent call last):
  File "/home/snandy/climate-models/spatial-robustness/systematic-generalization/sysgen.py", line 5, in <module>
    from climate_learn.utils.datetime import Year, Days, Hours
  File "/home/snandy/climate-learn-sys-gen/src/climate_learn/utils/__init__.py", line 1, in <module>
    from .visualize import *
  File "/home/snandy/climate-learn-sys-gen/src/climate_learn/utils/visualize.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/_path.cpython-310-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "/home/snandy/climate-models/spatial-robustness/systematic-generalization/sysgen.py", line 5, in <module>
    from climate_learn.utils.datetime import Year, Days, Hours
  File "/home/snandy/climate-learn-sys-gen/src/climate_learn/utils/__init__.py", line 1, in <module>
    from .visualize import *
  File "/home/snandy/climate-learn-sys-gen/src/climate_learn/utils/visualize.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/snandy/miniconda3/envs/climate-models1/lib/python3.10/site-packages/matplotlib/_path.cpython-310-x86_64-linux-gnu.so)
